version: "3.7"

services:

  www:
    container_name: www
    build:
      dockerfile: ./infra/docker/www/Dockerfile
      target: develop
      context: .
      dockerfile: ./infra/docker/www/Dockerfile
      target: develop
      context: .
    image: tech-notebook-www:latest
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
    networks:
      - default
      
  builder:
    container_name: builder
    build:
      dockerfile: ./infra/docker/builder/Dockerfile
      target: develop
      context: .
    image: tech-notebook-builder:latest
    tty: true
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
    depends_on:
      - www
    networks:
      - default