version: "3.7"

services:

  www:
    container_name: www
    build:
      context: .
      dockerfile: ./infra/docker/www/Dockerfile
    image: tech-notebook-www:latest
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/tech-notebook
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
      
  builder:
    container_name: builder
    build:
      context: .
      dockerfile: ./infra/docker/builder/Dockerfile
    image: tech-notebook-builder:latest
    tty: true
    volumes:
      - ./app:/var/www/tech-notebook
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
    depends_on:
      - www