version: "3.7"

services:
  web:
    container_name: sphinx
    build:
      context: .
      dockerfile: infra/web/Dockerfile
    tty: true
    volumes:
      - ./:/var/www/sphinx
      - ./logs/web:/tmp
    ports:
      - "8000:80"