# バージョン
version: 2

# ジョブの設定
jobs:  
  push:
    docker:
      - image: docker:stable-git
    # 作業ディレクトリの指定
    working_directory: ~
    steps:
      # NOTE: Docker in Docker 問題に対処
      - setup_remote_docker
      - run:
          # NOTE: checkoutが日本語を認識できないので対処
          name: Setup git config
          command: git config --global core.quotepath false
      - checkout
      - run:
          name: Build builder
          command: docker build -f infra/docker/builder/Dockerfile -t ${DOCKER_USER}/tech-notebook_builder:latest .
      - run:
          name: Build www
          command: docker build -f infra/docker/www/Dockerfile -t ${DOCKER_USER}/tech-notebook_www:latest .
      - run:
          name: Login to docker hub
          command: echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
      - run:
          name: Push image
          command: docker push ${DOCKER_USER}/tech-notebook_builder:latest
      - run:
          name: Push image
          command: docker push ${DOCKER_USER}/tech-notebook_www:latest

  build:
    docker:
      - image: hirokihasegawa/tech-notebook_builder:latest
    # 作業ディレクトリの指定
    working_directory: ~/tech-notebook
    steps:
      - run:
          # NOTE: checkoutが日本語を認識できないので対処
          name: Setup git config
          command: git config --global core.quotepath false
      - checkout
      - run:
          # Htmlの生成
          name: Build html
          command: make html
      - run:
          # 格納ディレクトリの掃除
          name: Clean up html
          command: make clean

# 実行の順番を定義
workflows:
  version: 2
  # Workflow名
  push_and_build:
    jobs:
      - push
      - build:
          # pushステップが成功したら実行
          requires:
            - push