# バージョン
version: 2.1

# AWS-ECRパッケージを使用．
orbs:
  aws-ecr: circleci/aws-ecr@4.0.4

executors:
  machine-type:
    machine: true
    working_directory: ~/tech-notebook

# 実行の順番を定義
workflows:
  version: 2.1
  # Workflow名
  build-push:
    jobs:
      # Docker Hub
      - push-images
      # AWS ECR builder
      - push-builder-to-ecr:
          requires:
            - build
      # AWS ECR www
      - push-www-to-ecr:
          requires:
            - build
      - build:
          requires:
            - push-images

# ジョブの設定
jobs:
  push-images:
    # ホスト（CircleCI）環境の設定
    executor: machine-type
    steps:
      - run:
          # -- NOTE: checkoutが日本語を認識できないので対処
          name: Setup git config
          command: |
            git config --global core.quotepath false
      - checkout
      - run:
          name: Build builder
          # -- NOTE: CircleCIのディレクトリは，/root/project(=tech-notebook)/
          command: |
            docker build -f infra/docker/builder/Dockerfile -t ${DOCKER_USER}/${REPOSITORY_NAME_BUILDER} .
      - run:
          name: Build www
          command: |
            docker build -f infra/docker/www/Dockerfile -t ${DOCKER_USER}/${REPOSITORY_NAME_WWW} .
      - run:
          name: Login to docker hub
          command: |
            echo ${DOCKER_PASS} |
            docker login -u ${DOCKER_USER} --password-stdin
      - run:
          name: Push builder
          command: |
            docker push ${DOCKER_USER}/${REPOSITORY_NAME_BUILDER}:${VERSION}
      - run:
          name: Push www
          command: |
            docker push ${DOCKER_USER}/${REPOSITORY_NAME_WWW}:${VERSION}
  
  push-builder-to-ecr:
    executor: machine-type
    steps:
      - checkout
      # -- NOTE: env_var_name型とstring型の間で，変数展開の記述方法が異なる
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          dockerfile: "infra/docker/builder/Dockerfile"
          path: "."
          region: AWS_REGION
          repo: ${REPOSITORY_NAME_BUILDER}
          tag: ${VERSION}
  
  push-www-to-ecr:
    executor: machine-type
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          dockerfile: "infra/docker/www/Dockerfile"
          path: "."
          region: AWS_REGION
          repo: ${REPOSITORY_NAME_WWW}
          tag: ${VERSION}
    
  build:
    # ホスト（CircleCI）環境の設定
    docker:
      - image: ${DOCKER_USER}/${REPOSITORY_NAME_BUILDER}:${VERSION}
    # 作業ディレクトリの設定
    steps:
      - run:
          # -- NOTE: checkoutが日本語を認識できないので対処
          name: Setup git config
          command: |
            git config --global core.quotepath false
      - checkout
      - run:
          # Htmlの生成
          name: Build html
          command: |
            make html
      - run:
          # 格納ディレクトリの掃除
          name: Clean up html
          command: |
            make clean