# バージョン
version: 2.1

# AWSへの接続準備
orbs:
  aws-ecr: circleci/aws-ecr@6.0.0

# ジョブの設定
jobs:
  push:
    docker:
      - image: docker:stable-git
    # 作業ディレクトリの指定
    working_directory: ~/
    steps:
      # NOTE: Docker in Docker 問題に対処
      - setup_remote_docker
      - run:
          # NOTE: checkoutが日本語を認識できないので対処
          name: Setup git config
          command: |
            git config --global core.quotepath false
      - checkout
      - run:
          name: Build builder
          command: |
            docker build -f infra/docker/builder/Dockerfile -t ${DOCKER_USER}./.${APP_NAME}_builder .
      - run:
          name: Build www
          command: |
            docker build -f infra/docker/www/Dockerfile -t ${DOCKER_USER}/${APP_NAME}_www .
      - run:
          name: Login to docker hub
          command: |
            echo "${DOCKER_PASS}" |
            docker login -u "${DOCKER_USER}" --password-stdin
      - run:
          name: Push builder
          command: |
            docker push ${DOCKER_USER}/${APP_NAME}_builder:latest
      - run:
          name: Push www
          command: |
            docker push ${DOCKER_USER}/${APP_NAME}_www:latest

  build:
    docker:
      - image: ${DOCKER_USER}/${APP_NAME}_builder:latest
    # 作業ディレクトリの指定
    working_directory: ~/${APP_NAME}
    steps:
      - run:
          # NOTE: checkoutが日本語を認識できないので対処
          name: Setup git config
          command: |
            git config --global core.quotepath false
      - checkout
      - run:
          # Htmlの生成
          name: Build html
          command: |
            make html
      - run:
          # 格納ディレクトリの掃除
          name: Clean up html
          command: |
            make clean

# 実行の順番を定義
workflows:
  version: 2.1
  # Workflow名
  build-push-test:
    jobs:
      # Docker Hub
      - push
      # AWS ECR builder
      - aws-ecr/build-and-push-image:
          account-url: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
          aws-access-key-id: ${AWS_ACCESS_KEY}
          aws-secret-access-key: ${AWS_SECRET_KEY}
          dockerfile: Dockerfile
          path: infra/docker/builder/Dockerfile
          region: ${AWS_REGION}
          repo: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APP_NAME}_builder
          tag: latest
          requires:
            - build
      # AWS ECR www
      - aws-ecr/build-and-push-image:
          account-url: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
          aws-access-key-id: ${AWS_ACCESS_KEY}
          aws-secret-access-key: ${AWS_SECRET_KEY}
          dockerfile: Dockerfile
          path: infra/docker/www/Dockerfile
          region: ${AWS_REGION}
          repo: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APP_NAME}_www
          tag: latest
          requires:
            - build
      - build:
          requires:
            - push