# バージョン
version: 2

# ジョブの設定
jobs:
  build:
    docker:
      - image: hirokihasegawa/tech-notebook_builder

    # 作業ディレクトリの作成
    working_directory: ~/tech-notebook

    # 実行コマンド
    steps:
      - run:
          # Gitの日本語を有効化
          name: Setup git config
          command: git config --global core.quotepath false
      - checkout
      - run:
          # Htmlの生成
          name: Build html
          command: make html
      - run:
          # 格納ディレクトリの掃除
          name: Clean up html
          command: make clean